apiVersion: v1
kind: ConfigMap
metadata:
  name: ragnroll-devenv
data:
  NEO4J_URI: neo4j://ragnroll-neo4j:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: neo4jpass
  NEO4J_DATABASE: neo4j
  OPENAI_API_KEY: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ragnroll-neo4j-config
data:
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_apoc_import_file_use__neo4j__config: "true"
  NEO4J_PLUGINS: '["apoc"]'
  NEO4J_AUTH: "neo4j/neo4jpass"
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "eval"
---

