version: '3.7'
services:
  devcontainer:
    userns_mode: keep-id:uid=1000,gid=1000
    image: registry.gitlab.com/abyres/releases/python-flutter-devcontainer:py3.11-flutter3.16.9
    command: tail -f /dev/null
    environment:
      - NEO4J_DATABASE=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4jpass
      - NEO4J_URI=bolt://neo4j:7687
    volumes: 
      - ..:/workspace:cached
      - ~/.cache:/home/user/.cache
  neo4j:
    userns_mode: keep-id:uid=7474,gid=7474
    image: docker.io/neo4j:5.16.0-enterprise-ubi8
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_AUTH=neo4j/neo4jpass
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=eval
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j-data:/data

